apiVersion: v1
kind: Service
metadata:
  name: contosso-air
  namespace: sample-app-namespace-1743513140465
  labels:
    app.kubernetes.io/name: contosso-air
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: contosso-air
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000